# add benchmarks via Makefile
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.toSSA]
pipeline = [
    "bril2json",
    "python3 to_ssa.py",
    "brili -p {args}",
]

[runs.roundTrip]
pipeline = [
    "bril2json",
    "python3 to_ssa.py",
    "python3 ../l3/dce.py",
    "python3 ~/bril/examples/from_ssa.py",
    "brili -p {args}",
]

[runs.roundTripBl]
pipeline = [
    "bril2json",
    "python3 ~/bril/examples/to_ssa.py",
    "python3 ../l3/dce.py",
    "python3 ~/bril/examples/from_ssa.py",
    "brili -p {args}",
]
